line-length = 120
indent-width = 4

# Include the notebook files
extend-include = ["*.ipynb"]

[lint]
# Enabled rules
select = [
    "E", # pycodestyle
    "F", # Flake8-return
    "C90", # McCabe
    "I", # Isort
    "D", # Pydocstyle
    "N", # pep8-naming
    "PT", # Flake8-pytest-style
    "ARG", # Flake8-unused-arguments
    "RSE", # Flake8-raise
    "RET", # Flake8-return
    "TID", # Flake8-tidy-imports
    "ERA", # eradicate
    "PTH", # pathlib
]

# Ignore some errors
ignore = [
    "D100", # Missing docstring in public module
    "D104", # Missing docstring in public package
    "D105", # Missing docstring in magic method
    "D203", # 1 blank line required before class docstring
    "D213" # Multi-line docstring summary should start at the second line
    ]


[lint.per-file-ignores]
"__init__.py" = ["F401"] # __init__.py can have unused imports


[format]
quote-style = "single"
